export default{async fetch(request,env){try{return await route(request,env)}catch(e){return new Response("Error: "+e.message,{status:500})}}};
async function route(req,env){
var url=new URL(req.url),p=url.pathname,m=req.method;
await init(env);
if(p==="/api/poll/vote"&&m==="POST")return apiPollVote(req,env);
if(p==="/api/upload"&&m==="POST")return apiUpload(req,env);
if(/^\/img\/(.+)$/.test(p))return apiImg(env,RegExp.$1);
if(p==="/favicon.svg")return favico();
if(p==="/admin"){if(m==="GET")return html(pgLogin());if(m==="POST")return doLogin(req,env)}
if(p==="/admin/logout")return doLogout();
if(p==="/admin/dashboard")return auth(env,req,async()=>html(await pgDash(env)));
if(p==="/admin/editor")return auth(env,req,async()=>html(await pgEditor(env)));
if(/^\/admin\/editor\/(.+)$/.test(p)){var eid=RegExp.$1;return auth(env,req,async()=>html(await pgEditor(env,eid)))}
if(p==="/admin/save"&&m==="POST")return auth(env,req,()=>actSave(req,env));
if(/^\/admin\/del\/(.+)$/.test(p)&&m==="POST"){var did=RegExp.$1;return auth(env,req,()=>actDel(env,did))}
if(/^\/admin\/pin\/(.+)$/.test(p)&&m==="POST"){var pid2=RegExp.$1;return auth(env,req,()=>actPin(env,pid2))}
if(p==="/admin/cats")return auth(env,req,async()=>html(await pgCats(env)));
if(p==="/admin/cat/add"&&m==="POST")return auth(env,req,()=>actAddCat(req,env));
if(/^\/admin\/cat\/del\/(.+)$/.test(p)&&m==="POST"){var cdid=RegExp.$1;return auth(env,req,()=>actDelCat(env,cdid))}
if(p==="/admin/settings")return auth(env,req,async()=>html(await pgSettings(env)));
if(p==="/admin/sett/save"&&m==="POST")return auth(env,req,()=>actSaveSett(req,env));
if(p==="/"||p==="")return html(await pgHome(env));
if(/^\/category\/(.+)$/.test(p))return html(await pgHome(env,decodeURIComponent(RegExp.$1)));
if(/^\/post\/(.+)$/.test(p))return html(await pgPost(env,RegExp.$1));
return new Response("404",{status:404})}
function hex(n){var a=new Uint8Array(n);crypto.getRandomValues(a);return[...a].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function sha(s){var buf=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function html(s){return new Response(s,{headers:{"Content-Type":"text/html;charset=utf-8"}})}
function redir(u){return new Response(null,{status:302,headers:{Location:u}})}
function jsonR(o,s){return new Response(JSON.stringify(o),{status:s||200,headers:{"Content-Type":"application/json"}})}
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function ago(ts){var d=Date.now()-ts;if(d<60000)return"\u521a\u521a";if(d<3600000)return Math.floor(d/60000)+"\u5206\u949f\u524d";if(d<86400000)return Math.floor(d/3600000)+"\u5c0f\u65f6\u524d";if(d<2592000000)return Math.floor(d/86400000)+"\u5929\u524d";return new Date(ts).toLocaleDateString("zh-CN")}
function ckm(cats){var m={};(cats||[]).forEach(c=>m[c.id]=c);return m}
function excerpt(h){return String(h||"").replace(/<[^>]*>/g,"").replace(/\s+/g," ").trim().slice(0,140)}
async function auth(env,req,fn){var ck=req.headers.get("Cookie")||"";var m=ck.match(/bt=([^;]+)/);if(m&&await env.BLOG_KV.get("sess:"+m[1])){var r=await fn();return r instanceof Response?r:html(r)}return redir("/admin")}
async function init(env){if(await env.BLOG_KV.get("settings"))return;var salt=hex(16);await env.BLOG_KV.put("settings",JSON.stringify({blogName:"\u674e\u529b\u7684blog",pwdHash:await sha(salt+"admin"),salt}));await env.BLOG_KV.put("cats",JSON.stringify([{id:"tech",name:"\u6280\u672f",color:"#0284c7"},{id:"life",name:"\u751f\u6d3b",color:"#059669"},{id:"think",name:"\u968f\u60f3",color:"#d97706"}]));var sid="seed001";await env.BLOG_KV.put("c:"+sid,JSON.stringify({content:'<h2>\u6b22\u8fce\u6765\u5230\u674e\u529b\u7684blog</h2><p>\u57fa\u4e8e Cloudflare Workers \u7684\u535a\u5ba2\u7cfb\u7edf</p><blockquote>\u524d\u5f80<a href="/admin">\u7ba1\u7406\u540e\u53f0</a>\u5f00\u59cb\u521b\u5efa\u6587\u7ae0</blockquote>',polls:{}}));await env.BLOG_KV.put("arts",JSON.stringify([{id:sid,title:"\u6b22\u8fce\u6765\u5230\u674e\u529b\u7684blog",catId:"tech",createdAt:Date.now(),updatedAt:Date.now(),pinned:true,excerpt:"\u57fa\u4e8e Cloudflare Workers \u7684\u535a\u5ba2"}]))}
function fonts(){return '<link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Lora:ital,wght@0,400;0,500;0,600;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">'}
function styles(){var q=String.fromCharCode(39);var c=[];
c.push("*{margin:0;padding:0;box-sizing:border-box}");
c.push(":root{--bg:#f0f9ff;--surface:#fff;--accent:#0284c7;--accent-l:#38bdf8;--accent-d:#0369a1;--accent-s:#e0f2fe;--green:#059669;--green-s:#d1fae5;--amber:#d97706;--amber-s:#fef3c7;--red:#dc2626;--text:#0f172a;--text2:#475569;--text3:#94a3b8;--border:#e2e8f0;--r:12px;--r-sm:8px;--shadow:0 1px 3px rgba(0,0,0,.06),0 4px 12px rgba(14,165,233,.06);--shadow-h:0 4px 12px rgba(0,0,0,.08),0 8px 24px rgba(14,165,233,.1);--ff:"+q+"Plus Jakarta Sans"+q+",system-ui,sans-serif;--ff-body:"+q+"Lora"+q+",Georgia,serif;--ff-mono:"+q+"JetBrains Mono"+q+",Consolas,monospace;--max-w:1100px;--content-w:780px}");
c.push("html{scroll-behavior:smooth} body{font-family:var(--ff-body);color:var(--text);background:var(--bg);line-height:1.75;min-height:100vh}");
c.push("a{color:var(--accent);text-decoration:none;transition:color .2s} a:hover{color:var(--accent-d)}");
c.push(".site-header{background:linear-gradient(135deg,#0ea5e9 0%,#06b6d4 40%,#10b981 100%);position:relative;overflow:hidden}");
c.push(".site-header::before{content:"+q+q+";position:absolute;inset:0;background-image:radial-gradient(circle,rgba(255,255,255,.12) 1.5px,transparent 1.5px);background-size:24px 24px;pointer-events:none}");
c.push(".header-inner{max-width:var(--max-w);margin:0 auto;padding:2.5rem 2rem 2rem;position:relative;z-index:1}");
c.push(".logo{font-family:var(--ff);font-size:2rem;font-weight:700;color:#fff!important;letter-spacing:-.02em;text-shadow:0 2px 8px rgba(0,0,0,.15)}");
c.push(".cat-nav{margin-top:1rem;display:flex;flex-wrap:wrap;gap:.5rem}");
c.push(".cat-link{font-family:var(--ff);font-size:.875rem;font-weight:500;color:rgba(255,255,255,.85)!important;background:rgba(255,255,255,.15);backdrop-filter:blur(8px);padding:.35rem 1rem;border-radius:999px;transition:all .2s;border:1px solid rgba(255,255,255,.2)}");
c.push(".cat-link:hover,.cat-link.active{background:rgba(255,255,255,.95);color:var(--accent)!important;border-color:transparent}");
c.push(".container{max-width:var(--max-w);margin:0 auto;padding:2rem}");
c.push(".section-title{font-family:var(--ff);font-size:1.25rem;font-weight:600;margin-bottom:1.25rem}");
c.push(".article-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:1.25rem;margin-bottom:2.5rem}");
c.push(".article-card{background:var(--surface);border-radius:var(--r);padding:1.5rem;box-shadow:var(--shadow);border:1px solid var(--border);transition:all .25s ease;display:block;text-decoration:none;color:inherit;animation:fadeUp .5s ease both}");
c.push(".article-card:hover{transform:translateY(-4px);box-shadow:var(--shadow-h);border-color:var(--accent-l);color:inherit}");
c.push(".card-meta{display:flex;align-items:center;gap:.5rem;margin-bottom:.75rem;flex-wrap:wrap}");
c.push(".card-cat{font-family:var(--ff);font-size:.75rem;font-weight:600;padding:.2rem .6rem;border-radius:999px;color:#fff}");
c.push(".card-pin{font-family:var(--ff);font-size:.7rem;font-weight:600;padding:.15rem .5rem;border-radius:999px;background:var(--amber-s);color:var(--amber)}");
c.push(".card-title{font-family:var(--ff);font-size:1.15rem;font-weight:600;color:var(--text);margin-bottom:.5rem;line-height:1.4}");
c.push(".card-excerpt{font-size:.9rem;color:var(--text2);line-height:1.6;margin-bottom:.75rem}");
c.push(".card-date{font-family:var(--ff-mono);font-size:.75rem;color:var(--text3)}");
c.push("@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}");
c.push(".post-container{max-width:var(--content-w);margin:0 auto;padding:2rem}");
c.push(".post-back{font-family:var(--ff);font-size:.875rem;color:var(--text2);margin-bottom:1.5rem;display:inline-block} .post-back:hover{color:var(--accent)}");
c.push(".post-cat{font-family:var(--ff);font-size:.8rem;font-weight:600;padding:.25rem .75rem;border-radius:999px;color:#fff;display:inline-block;margin-bottom:.75rem}");
c.push(".post-title{font-family:var(--ff);font-size:2rem;font-weight:700;line-height:1.3;color:var(--text);margin-bottom:.5rem}");
c.push(".post-date{font-family:var(--ff-mono);font-size:.85rem;color:var(--text3)}");
c.push(".post-divider{border:none;height:2px;background:linear-gradient(90deg,var(--accent-l),var(--green),transparent);margin:1.5rem 0 2rem}");
c.push(".post-content{font-size:1.05rem;line-height:1.85}");
c.push(".post-content h1,.post-content h2,.post-content h3{font-family:var(--ff);margin:2rem 0 .75rem}");
c.push(".post-content h1{font-size:1.75rem} .post-content h2{font-size:1.4rem} .post-content h3{font-size:1.15rem}");
c.push(".post-content p{margin-bottom:1rem} .post-content img{max-width:100%;border-radius:var(--r-sm);margin:1rem 0}");
c.push(".post-content blockquote{border-left:4px solid var(--accent-l);padding:.75rem 1.25rem;background:var(--accent-s);border-radius:0 var(--r-sm) var(--r-sm) 0;margin:1rem 0;color:var(--text2)}");
c.push(".post-content pre{background:#1e293b;color:#e2e8f0;padding:1rem;border-radius:var(--r-sm);overflow-x:auto;font-family:var(--ff-mono);font-size:.875rem;margin:1rem 0}");
c.push(".post-content code{font-family:var(--ff-mono);background:var(--accent-s);padding:.15rem .4rem;border-radius:4px;font-size:.9em} .post-content pre code{background:none;padding:0}");
c.push(".post-content ul,.post-content ol{margin:.75rem 0 .75rem 1.5rem} .post-content a{color:var(--accent);border-bottom:1px solid var(--accent-l)}");
c.push(".poll-widget{background:linear-gradient(135deg,var(--accent-s),var(--green-s));border:2px solid var(--accent-l);border-radius:var(--r);padding:1.5rem;margin:1.5rem 0}");
c.push(".poll-w-title{font-family:var(--ff);font-size:1.1rem;font-weight:600;margin-bottom:1rem}");
c.push(".poll-w-opt{margin-bottom:.75rem}");
c.push(".poll-w-btn{width:100%;text-align:left;font-family:var(--ff);font-size:.9rem;font-weight:500;padding:.6rem 1rem;border:2px solid var(--border);border-radius:var(--r-sm);background:var(--surface);color:var(--text);cursor:pointer;transition:all .2s;position:relative;overflow:hidden;display:flex;justify-content:space-between;align-items:center}");
c.push(".poll-w-btn:hover:not(:disabled){border-color:var(--accent);background:var(--accent-s)} .poll-w-btn:disabled{cursor:default;opacity:.9}");
c.push(".poll-w-bar{position:absolute;left:0;top:0;bottom:0;background:rgba(14,165,233,.12);transition:width .5s ease;border-radius:var(--r-sm)}");
c.push(".poll-w-text{position:relative;z-index:1}");
c.push(".poll-w-pct{position:relative;z-index:1;font-family:var(--ff-mono);font-size:.85rem;color:var(--accent);font-weight:600}");
c.push(".poll-w-total{font-family:var(--ff-mono);font-size:.8rem;color:var(--text3);margin-top:.5rem;text-align:right}");
c.push(".poll-embed{background:linear-gradient(135deg,var(--accent-s),var(--green-s));border:2px dashed var(--accent-l);border-radius:var(--r-sm);padding:1rem;margin:1rem 0}");
c.push(".empty-state{text-align:center;padding:4rem 2rem;color:var(--text3)}");
c.push(".site-footer{text-align:center;padding:2rem;font-family:var(--ff);font-size:.8rem;color:var(--text3);border-top:1px solid var(--border);margin-top:2rem}");
c.push(".admin-nav{background:#0f172a;padding:0 2rem;display:flex;align-items:center;position:sticky;top:0;z-index:100;box-shadow:0 2px 8px rgba(0,0,0,.2)}");
c.push(".admin-brand{font-family:var(--ff);font-weight:700;color:#fff;font-size:1rem;padding:.9rem 1.5rem .9rem 0;margin-right:1rem;border-right:1px solid rgba(255,255,255,.1);white-space:nowrap}");
c.push(".admin-links{display:flex;flex-wrap:wrap}");
c.push(".admin-link{font-family:var(--ff);font-size:.85rem;font-weight:500;color:rgba(255,255,255,.6)!important;padding:.9rem 1rem;border-bottom:2px solid transparent;transition:all .2s} .admin-link:hover{color:#fff!important} .admin-link.active{color:#fff!important;border-bottom-color:var(--accent-l)}");
c.push(".admin-right{margin-left:auto;display:flex;gap:.5rem;align-items:center}");
c.push(".admin-body{max-width:var(--max-w);margin:0 auto;padding:2rem}");
c.push(".admin-h1{font-family:var(--ff);font-size:1.5rem;font-weight:700;margin-bottom:1.5rem}");
c.push(".stats{display:flex;gap:1rem;margin-bottom:2rem;flex-wrap:wrap}");
c.push(".stat-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--r);padding:1.25rem 1.5rem;min-width:140px;flex:1}");
c.push(".stat-num{font-family:var(--ff);font-size:2rem;font-weight:700;color:var(--accent)}");
c.push(".stat-label{font-family:var(--ff);font-size:.8rem;color:var(--text3)}");
c.push(".btn{font-family:var(--ff);font-size:.85rem;font-weight:600;padding:.5rem 1.25rem;border-radius:var(--r-sm);border:none;cursor:pointer;transition:all .2s;display:inline-flex;align-items:center;gap:.35rem;text-decoration:none;line-height:1.4}");
c.push(".btn-p{background:var(--accent);color:#fff} .btn-p:hover{background:var(--accent-d)}");
c.push(".btn-g{background:var(--green);color:#fff} .btn-g:hover{background:#047857}");
c.push(".btn-a{background:var(--amber);color:#fff} .btn-a:hover{background:#b45309}");
c.push(".btn-r{background:var(--red);color:#fff} .btn-r:hover{background:#b91c1c}");
c.push(".btn-o{background:transparent;color:var(--text2);border:1.5px solid var(--border)} .btn-o:hover{border-color:var(--accent);color:var(--accent)}");
c.push(".btn-sm{font-size:.75rem;padding:.35rem .8rem}");
c.push(".art-list{display:flex;flex-direction:column;gap:.75rem}");
c.push(".art-item{background:var(--surface);border:1px solid var(--border);border-radius:var(--r-sm);padding:1rem 1.25rem;display:flex;align-items:center;gap:1rem;transition:all .2s;flex-wrap:wrap} .art-item:hover{border-color:var(--accent-l);box-shadow:var(--shadow)}");
c.push(".art-info{flex:1;min-width:200px} .art-t{font-family:var(--ff);font-weight:600;font-size:1rem;margin-bottom:.25rem}");
c.push(".art-meta{font-family:var(--ff-mono);font-size:.75rem;color:var(--text3);display:flex;gap:.75rem;align-items:center}");
c.push(".art-dot{width:8px;height:8px;border-radius:50%;display:inline-block} .art-acts{display:flex;gap:.5rem;flex-wrap:wrap}");
c.push(".fg{margin-bottom:1.25rem} .fl{font-family:var(--ff);font-size:.85rem;font-weight:600;display:block;margin-bottom:.35rem}");
c.push(".fi,.fs{font-family:var(--ff-body);font-size:.95rem;padding:.6rem 1rem;border:1.5px solid var(--border);border-radius:var(--r-sm);background:var(--surface);color:var(--text);width:100%;transition:border-color .2s;outline:none} .fi:focus,.fs:focus{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-s)}");
c.push(".editor-wrap{background:var(--surface);border:1.5px solid var(--border);border-radius:var(--r);overflow:hidden;display:flex;flex-direction:column}");
c.push(".toolbar{background:#f8fafc;border-bottom:1px solid var(--border);padding:.5rem;display:flex;flex-wrap:wrap;gap:.25rem;align-items:center;flex-shrink:0}");
c.push(".tb-sep{width:1px;height:24px;background:var(--border);margin:0 .35rem}");
c.push(".tb{font-family:var(--ff);font-size:.8rem;font-weight:600;padding:.35rem .6rem;border:1px solid transparent;border-radius:6px;background:transparent;color:var(--text2);cursor:pointer;transition:all .15s;white-space:nowrap} .tb:hover{background:var(--accent-s);color:var(--accent);border-color:var(--accent-l)}");
c.push(".editor-area{min-height:500px;padding:1.5rem;outline:none;font-family:var(--ff-body);font-size:1rem;line-height:1.8;color:var(--text);flex:1;overflow-y:auto} .editor-area img{max-width:100%;border-radius:8px}");
c.push(".modal-bg{position:fixed;inset:0;background:rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;z-index:1000;backdrop-filter:blur(4px)}");
c.push(".modal-box{background:var(--surface);border-radius:var(--r);padding:2rem;width:90%;max-width:480px;box-shadow:0 20px 60px rgba(0,0,0,.2)}");
c.push(".modal-h{font-family:var(--ff);font-size:1.25rem;font-weight:700;margin-bottom:1.25rem} .modal-btns{display:flex;gap:.75rem;justify-content:flex-end;margin-top:1.5rem}");
c.push(".s-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--r);padding:1.5rem;margin-bottom:1.5rem}");
c.push(".s-card-t{font-family:var(--ff);font-size:1.1rem;font-weight:600;margin-bottom:1rem;padding-bottom:.75rem;border-bottom:1px solid var(--border)}");
c.push("@media(max-width:768px){.header-inner{padding:2rem 1.25rem 1.5rem} .logo{font-size:1.5rem} .container{padding:1.25rem} .article-grid{grid-template-columns:1fr} .post-container{padding:1.25rem} .post-title{font-size:1.5rem} .admin-nav{padding:0 .5rem;flex-wrap:wrap} .admin-body{padding:1.25rem} .art-item{flex-direction:column;align-items:flex-start} .stats{flex-direction:column}}");
return '<style>'+c.join(" ")+'</style>'}
function adminW(t,b,tab){return'<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(t)+'</title>'+fonts()+styles()+'</head><body><nav class="admin-nav"><span class="admin-brand">\u674e\u529b\u7684blog \u00b7 \u540e\u53f0</span><div class="admin-links"><a href="/admin/dashboard" class="admin-link'+(tab==="d"?" active":"")+'">\u4eea\u8868\u677f</a><a href="/admin/editor" class="admin-link'+(tab==="e"?" active":"")+'">\u5199\u6587\u7ae0</a><a href="/admin/cats" class="admin-link'+(tab==="c"?" active":"")+'">\u5206\u7c7b</a><a href="/admin/settings" class="admin-link'+(tab==="s"?" active":"")+'">\u8bbe\u7f6e</a></div><div class="admin-right"><a href="/" class="btn btn-sm btn-o" style="color:rgba(255,255,255,.7);border-color:rgba(255,255,255,.2)">\u67e5\u770b</a><a href="/admin/logout" class="btn btn-sm btn-o" style="color:rgba(255,255,255,.7);border-color:rgba(255,255,255,.2)">\u9000\u51fa</a></div></nav><div class="admin-body">'+b+'</div></body></html>'}
async function pgHome(env,cat){var[st,cats,arts]=await Promise.all([env.BLOG_KV.get("settings","json"),env.BLOG_KV.get("cats","json"),env.BLOG_KV.get("arts","json")]);var s=st||{blogName:"\u674e\u529b\u7684blog"};var list=arts||[];if(cat)list=list.filter(a=>a.catId===cat);var pinned=list.filter(a=>a.pinned).sort((a,b)=>b.updatedAt-a.updatedAt);var normal=list.filter(a=>!a.pinned).sort((a,b)=>b.createdAt-a.createdAt);var cm=ckm(cats);function card(a){var c=cm[a.catId]||{name:"\u672a\u5206\u7c7b",color:"#94a3b8"};return'<a href="/post/'+a.id+'" class="article-card"><div class="card-meta"><span class="card-cat" style="background:'+c.color+'">'+esc(c.name)+'</span>'+(a.pinned?"<span class=\"card-pin\">\ud83d\udccc \u7f6e\u9876</span>":"")+'</div><div class="card-title">'+esc(a.title)+'</div><div class="card-excerpt">'+esc(a.excerpt||"")+'</div><div class="card-date">'+ago(a.createdAt)+'</div></a>'}var nav=(cats||[]).map(c=>'<a href="/category/'+c.id+'" class="cat-link'+(cat===c.id?" active":"")+'">'+esc(c.name)+'</a>').join("");return'<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(s.blogName)+'</title>'+fonts()+styles()+'</head><body><header class="site-header"><div class="header-inner"><a href="/" class="logo">'+esc(s.blogName)+'</a><nav class="cat-nav"><a href="/" class="cat-link'+(!cat?" active":"")+'">\u5168\u90e8</a>'+nav+'</nav></div></header><main class="container">'+(pinned.length?"<section><h2 class=\"section-title\">\ud83d\udccc \u7f6e\u9876</h2><div class=\"article-grid\">"+pinned.map(card).join("")+"</div></section>":"")+"<section>"+(!cat&&pinned.length?"<h2 class=\"section-title\">\u6700\u65b0\u6587\u7ae0</h2>":"")+"<div class=\"article-grid\">"+normal.map(card).join("")+"</div>"+(!pinned.length&&!normal.length?"<div class=\"empty-state\">\u6682\u65e0\u6587\u7ae0</div>":"")+"</section></main><footer class=\"site-footer\">&copy; "+new Date().getFullYear()+" "+esc(s.blogName)+" &middot; Powered by CF Workers</footer></body></html>"}
async function pgPost(env,id){var[st,cats,arts,raw]=await Promise.all([env.BLOG_KV.get("settings","json"),env.BLOG_KV.get("cats","json"),env.BLOG_KV.get("arts","json"),env.BLOG_KV.get("c:"+id)]);var s=st||{blogName:"\u674e\u529b\u7684blog"};var art=(arts||[]).find(a=>a.id===id);if(!art)return'<!DOCTYPE html><html><head><meta charset="utf-8"><title>404</title>'+fonts()+styles()+'</head><body><div style="text-align:center;padding:8rem 2rem"><h1 style="font-family:var(--ff);font-size:4rem;color:var(--accent)">404</h1><a href="/" class="btn btn-p">\u8fd4\u56de</a></div></body></html>';var cm2=ckm(cats);var cat=cm2[art.catId]||{name:"\u672a\u5206\u7c7b",color:"#94a3b8"};var ch="";if(raw){var d=typeof raw==="string"?JSON.parse(raw):raw;ch=d.content||""}ch=await renderPolls(ch,env);ch=ch.replace(/<a /g,'<a target="_blank" rel="noopener" ');var date=new Date(art.createdAt).toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric"});return'<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(art.title)+'</title>'+fonts()+styles()+'</head><body><header class="site-header"><div class="header-inner"><a href="/" class="logo">'+esc(s.blogName)+'</a></div></header><main class="post-container"><a href="/" class="post-back">&larr; \u8fd4\u56de</a><article><span class="post-cat" style="background:'+cat.color+'">'+esc(cat.name)+'</span><h1 class="post-title">'+esc(art.title)+'</h1><div class="post-date">'+date+'</div></article><hr class="post-divider"><div class="post-content">'+ch+'</div></main><footer class="site-footer">&copy; '+new Date().getFullYear()+" "+esc(s.blogName)+'</footer><script>async function votePoll(pid,idx){try{var r=await fetch("/api/poll/vote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pollId:pid,optionIndex:idx})});var d=await r.json();if(d.success)location.reload();else alert(d.error||"\u5931\u8d25")}catch(e){alert("\u7f51\u7edc\u9519\u8bef")}}<\/script></body></html>'}
async function renderPolls(content,env){var r=content,from=0;while(true){var si=r.indexOf("data-poll-id=",from);if(si===-1)break;var is2=r.indexOf('"',si),ie=r.indexOf('"',is2+1);if(is2===-1||ie===-1)break;var pid=r.substring(is2+1,ie);var ds=r.lastIndexOf("<div",si);if(ds===-1){from=ie;continue}var depth=0,pos=ds,de=-1;while(pos<r.length){if(r.substring(pos,pos+4)==="<div"){depth++;pos+=4}else if(r.substring(pos,pos+6)==="</div>"){depth--;if(depth===0){de=pos+6;break}pos+=6}else pos++}if(de===-1){from=ie;continue}var pd=await env.BLOG_KV.get("poll:"+pid,"json");if(pd){var total=pd.options.reduce((s,o)=>s+o.votes,0);var wh=buildPoll(pid,pd,total);r=r.substring(0,ds)+wh+r.substring(de);from=ds+wh.length}else{from=de}}return r}
function buildPoll(pid,pd,total){return'<div class="poll-widget"><div class="poll-w-title">\ud83d\udcca '+esc(pd.title)+'</div>'+pd.options.map(function(o,i){var pct=total>0?Math.round(o.votes/total*100):0;return'<div class="poll-w-opt"><button class="poll-w-btn" onclick="votePoll(\''+pid+'\','+i+')"><span class="poll-w-bar" style="width:'+pct+'%"></span><span class="poll-w-text">'+esc(o.text)+'</span><span class="poll-w-pct">'+pct+'%</span></button></div>'}).join("")+'<div class="poll-w-total">\u5171 '+total+' \u7968</div></div>'}
function pgLogin(){return'<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>\u767b\u5f55</title>'+fonts()+styles()+'</head><body style="display:flex;align-items:center;justify-content:center;min-height:100vh;background:linear-gradient(135deg,#0ea5e9 0%,#06b6d4 50%,#10b981 100%)"><div style="background:#fff;border-radius:16px;padding:2.5rem;width:90%;max-width:380px;box-shadow:0 20px 60px rgba(0,0,0,.15)"><h1 style="font-family:var(--ff);font-size:1.5rem;text-align:center;margin-bottom:.5rem">\u674e\u529b\u7684blog</h1><p style="text-align:center;font-family:var(--ff);font-size:.85rem;color:var(--text3);margin-bottom:2rem">\u7ba1\u7406\u540e\u53f0</p><form method="POST" action="/admin"><div class="fg"><label class="fl">\u5bc6\u7801</label><input type="password" name="pwd" class="fi" required autofocus></div><button type="submit" class="btn btn-p" style="width:100%;justify-content:center;padding:.7rem">\u767b \u5f55</button></form></div></body></html>'}
async function doLogin(req,env){var fd=await req.formData();var pwd=fd.get("pwd")||"";var settings=await env.BLOG_KV.get("settings","json");if(await sha(settings.salt+pwd)!==settings.pwdHash)return html(pgLogin());var token=hex(32);await env.BLOG_KV.put("sess:"+token,"1",{expirationTtl:86400});return new Response(null,{status:302,headers:{Location:"/admin/dashboard","Set-Cookie":"bt="+token+"; Path=/; HttpOnly; SameSite=Lax"}})}
function doLogout(){return new Response(null,{status:302,headers:{Location:"/admin","Set-Cookie":"bt=; Path=/; HttpOnly; Max-Age=0"}})}
async function pgDash(env){var[cats,arts]=await Promise.all([env.BLOG_KV.get("cats","json"),env.BLOG_KV.get("arts","json")]);var list=arts||[];var cm3=ckm(cats);var items=list.sort((a,b)=>(b.pinned?1:0)-(a.pinned?1:0)||b.createdAt-a.createdAt).map(a=>{var c=cm3[a.catId]||{name:"\u672a\u5206\u7c7b",color:"#94a3b8"};return'<div class="art-item"><div class="art-info"><div class="art-t">'+(a.pinned?"\ud83d\udccc ":"")+esc(a.title)+'</div><div class="art-meta"><span class="art-dot" style="background:'+c.color+'"></span>'+esc(c.name)+" \u00b7 "+ago(a.createdAt)+'</div></div><div class="art-acts"><a href="/admin/editor/'+a.id+'" class="btn btn-sm btn-o">\u7f16\u8f91</a><form method="POST" action="/admin/pin/'+a.id+'" style="display:inline"><button class="btn btn-sm btn-a">'+(a.pinned?"\u53d6\u6d88":"\u7f6e\u9876")+'</button></form><form method="POST" action="/admin/del/'+a.id+'" style="display:inline" onsubmit="return confirm(\'\u786e\u5b9a?\')"><button class="btn btn-sm btn-r">\u5220\u9664</button></form></div></div>'}).join("");return adminW("\u4eea\u8868\u677f",'<h1 class="admin-h1">\u4eea\u8868\u677f</h1><div class="stats"><div class="stat-card"><div class="stat-num">'+list.length+'</div><div class="stat-label">\u6587\u7ae0</div></div><div class="stat-card"><div class="stat-num">'+(cats||[]).length+'</div><div class="stat-label">\u5206\u7c7b</div></div><div class="stat-card"><div class="stat-num">'+list.filter(a=>a.pinned).length+'</div><div class="stat-label">\u7f6e\u9876</div></div></div><h2 style="font-family:var(--ff);font-size:1.1rem;margin-bottom:1rem">\u6587\u7ae0\u7ba1\u7406</h2><div class="art-list">'+(items||"<div style=\"color:var(--text3);padding:2rem;text-align:center\">\u6682\u65e0</div>")+'</div>',"d")}

async function pgEditor(env,id){var art=null,cd=null;if(id){var arts=await env.BLOG_KV.get("arts","json")||[];art=arts.find(a=>a.id===id);if(!art)return"\u6587\u7ae0\u4e0d\u5b58\u5728";var raw=await env.BLOG_KV.get("c:"+id);if(raw)cd=typeof raw==="string"?JSON.parse(raw):raw}var cats=await env.BLOG_KV.get("cats","json")||[];var content=cd?(cd.content||""):"";var polls=cd?(cd.polls||{}):{};var catOpts=cats.map(c=>'<option value="'+c.id+'"'+(art&&art.catId===c.id?" selected":"")+'>'+esc(c.name)+'</option>').join("");
var h='<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+(id?"\u7f16\u8f91":"\u5199\u6587\u7ae0")+'</title>'+fonts()+styles()+'</head><body>';
h+='<nav class="admin-nav"><span class="admin-brand">\u674e\u529b\u7684blog \u00b7 \u540e\u53f0</span><div class="admin-links">';
h+='<a href="/admin/dashboard" class="admin-link">\u4eea\u8868\u677f</a><a href="/admin/editor" class="admin-link active">\u5199\u6587\u7ae0</a><a href="/admin/cats" class="admin-link">\u5206\u7c7b</a><a href="/admin/settings" class="admin-link">\u8bbe\u7f6e</a>';
h+='</div><div class="admin-right"><a href="/admin/dashboard" class="btn btn-sm btn-o" style="color:rgba(255,255,255,.7);border-color:rgba(255,255,255,.2)">\u8fd4\u56de</a></div></nav>';
h+='<div class="admin-body"><input type="hidden" id="art-id" value="'+(id||"")+'">';
h+='<div style="display:flex;gap:1rem;margin-bottom:1rem;flex-wrap:wrap;align-items:end">';
h+='<div class="fg" style="flex:1;min-width:200px;margin-bottom:0"><label class="fl">\u6587\u7ae0\u6807\u9898</label><input type="text" id="art-title" class="fi" value="'+esc(art?art.title:"")+'" placeholder="\u6807\u9898"></div>';
h+='<div class="fg" style="min-width:150px;margin-bottom:0"><label class="fl">\u5206\u7c7b</label><select id="art-cat" class="fs">'+catOpts+'</select></div>';
h+='<button class="btn btn-g" onclick="doSave()" style="height:42px">\ud83d\udcbe \u4fdd\u5b58</button>';
h+='<a href="/admin/dashboard" class="btn btn-o" style="height:42px">\u53d6\u6d88</a></div>';
h+='<div class="editor-wrap"><div class="toolbar">';
h+='<button class="tb" onclick="ec(\'bold\')"><b>B</b></button>';
h+='<button class="tb" onclick="ec(\'italic\')"><i>I</i></button>';
h+='<button class="tb" onclick="ec(\'underline\')"><u>U</u></button>';
h+='<button class="tb" onclick="ec(\'strikethrough\')"><s>S</s></button>';
h+='<span class="tb-sep"></span>';
h+='<button class="tb" onclick="ef(\'h1\')">H1</button>';
h+='<button class="tb" onclick="ef(\'h2\')">H2</button>';
h+='<button class="tb" onclick="ef(\'h3\')">H3</button>';
h+='<span class="tb-sep"></span>';
h+='<button class="tb" onclick="ec(\'insertOrderedList\')">1.</button>';
h+='<button class="tb" onclick="ec(\'insertUnorderedList\')">&bull;</button>';
h+='<span class="tb-sep"></span>';
h+='<button class="tb" onclick="insLink()">\ud83d\udd17 \u94fe\u63a5</button>';
h+='<button class="tb" onclick="insImg()">\ud83d\uddbc \u56fe\u7247</button>';
h+='<button class="tb" onclick="document.getElementById(\'fup\').click()">\ud83d\udce4 \u4e0a\u4f20</button>';
h+='<button class="tb" onclick="openPoll()">\ud83d\udcca \u6295\u7968</button>';
h+='<span class="tb-sep"></span>';
h+='<button class="tb" onclick="ef(\'blockquote\')">\u275d \u5f15\u7528</button>';
h+='<button class="tb" onclick="insCode()">&lt;/&gt; \u4ee3\u7801</button>';
h+='<button class="tb" onclick="ec(\'insertHorizontalRule\')"> \u2014\u2014</button>';
h+='</div><div id="editor" class="editor-area" contenteditable="true">'+content+'</div></div>';
h+='<input type="file" id="fup" accept="image/*" style="display:none"></div>';
h+='<div id="pollModal" class="modal-bg" style="display:none"><div class="modal-box">';
h+='<div class="modal-h">\ud83d\udcca \u63d2\u5165\u6295\u7968</div>';
h+='<div class="fg"><label class="fl">\u6295\u7968\u6807\u9898</label><input type="text" id="pollTitle" class="fi" placeholder="\u6807\u9898"></div>';
h+='<div class="fg"><label class="fl">\u9009\u9879</label><div id="pollOpts">';
h+='<div class="poi" style="display:flex;gap:.5rem;margin-bottom:.5rem"><input type="text" class="fi" placeholder="\u9009\u9879 1" style="flex:1"><button class="btn btn-sm btn-r" onclick="rmOpt(this)" style="padding:.3rem .5rem">&times;</button></div>';
h+='<div class="poi" style="display:flex;gap:.5rem;margin-bottom:.5rem"><input type="text" class="fi" placeholder="\u9009\u9879 2" style="flex:1"><button class="btn btn-sm btn-r" onclick="rmOpt(this)" style="padding:.3rem .5rem">&times;</button></div>';
h+='</div><button class="btn btn-sm btn-o" onclick="addOpt()" style="margin-top:.25rem">+ \u6dfb\u52a0</button></div>';
h+='<div class="modal-btns"><button class="btn btn-o" onclick="closePoll()">\u53d6\u6d88</button><button class="btn btn-p" onclick="confirmPoll()">\u63d2\u5165</button></div></div></div>';

var s="<scr"+"ipt>";
s+="var editorPolls="+JSON.stringify(polls)+";";
s+="var ed=document.getElementById('editor');";
s+="function ec(c){ed.focus();document.execCommand(c,false,null)}";
s+="function ef(tag){ed.focus();document.execCommand('formatBlock',false,'<'+tag+'>')}";
s+="function insLink(){var u=prompt('\u94fe\u63a5:','https://');if(!u)return;ed.focus();var sel=window.getSelection();if(sel.toString()){document.execCommand('createLink',false,u)}else{document.execCommand('insertHTML',false,'<a href=\x22'+u+'\x22>'+u+'</a>')}}";
s+="function insImg(){var u=prompt('\u56fe\u7247:','https://');if(!u)return;ed.focus();document.execCommand('insertHTML',false,'<img src=\x22'+u+'\x22 style=\x22max-width:100%;border-radius:8px\x22><p><br></p>')}";
s+="document.getElementById('fup').addEventListener('change',async function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=async function(){try{var resp=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:r.result,type:f.type})});var d=await resp.json();if(d.url){ed.focus();document.execCommand('insertHTML',false,'<img src=\x22'+d.url+'\x22 style=\x22max-width:100%;border-radius:8px\x22><p><br></p>')}else alert('\u5931\u8d25')}catch(err){alert('\u9519\u8bef')}};r.readAsDataURL(f);e.target.value=''})";
s+="function insCode(){ed.focus();document.execCommand('insertHTML',false,'<pre><code>// code</code></pre><p><br></p>')}";
s+="function openPoll(){document.getElementById('pollModal').style.display='flex';document.getElementById('pollTitle').value=''}";
s+="function closePoll(){document.getElementById('pollModal').style.display='none'}";
s+="function addOpt(){var c=document.getElementById('pollOpts'),n=c.children.length+1,d=document.createElement('div');d.className='poi';d.style.cssText='display:flex;gap:.5rem;margin-bottom:.5rem';var inp=document.createElement('input');inp.type='text';inp.className='fi';inp.placeholder='\u9009\u9879 '+n;inp.style.flex='1';var btn=document.createElement('button');btn.className='btn btn-sm btn-r';btn.style.cssText='padding:.3rem .5rem';btn.textContent='\u00d7';btn.onclick=function(){rmOpt(btn)};d.appendChild(inp);d.appendChild(btn);c.appendChild(d)}";
s+="function rmOpt(b){if(document.getElementById('pollOpts').children.length>2)b.parentElement.remove()}";
s+="function confirmPoll(){var t=document.getElementById('pollTitle').value.trim();if(!t){alert('\u6807\u9898');return}var inputs=document.querySelectorAll('#pollOpts input');var opts=[];inputs.forEach(function(i){if(i.value.trim())opts.push(i.value.trim())});if(opts.length<2){alert('\u81f3\u5c112\u4e2a');return}var pid='p'+Date.now()+Math.random().toString(36).substr(2,5);editorPolls[pid]={title:t,options:opts};var h2='<div class=\x22poll-embed\x22 contenteditable=\x22false\x22 data-poll-id=\x22'+pid+'\x22 style=\x22background:linear-gradient(135deg,#e0f2fe,#d1fae5);border:2px dashed #7dd3fc;border-radius:12px;padding:16px;margin:16px 0\x22><div style=\x22font-weight:600;margin-bottom:8px\x22>\ud83d\udcca '+t.replace(/</g,'&lt;')+'</div>'+opts.map(function(o){return'<div style=\x22font-size:14px;padding:4px 0\x22>\u2022 '+o.replace(/</g,'&lt;')+'</div>'}).join('')+'</div><p><br></p>';ed.focus();document.execCommand('insertHTML',false,h2);closePoll()}";
s+="async function doSave(){var t=document.getElementById('art-title').value.trim();if(!t){alert('\u6807\u9898');return}var c=document.getElementById('art-cat').value;var id=document.getElementById('art-id').value;var body={id:id,title:t,catId:c,content:ed.innerHTML,polls:editorPolls};try{var r=await fetch('/admin/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.redirected||r.ok)window.location.href='/admin/dashboard';else alert('\u5931\u8d25')}catch(e){alert('\u9519\u8bef')}}";
s+="document.addEventListener('keydown',function(e){if(e.ctrlKey&&e.key==='s'){e.preventDefault();doSave()}})";
s+="<\/scr"+"ipt>";
return h+s+"</body></html>"}
async function pgCats(env){var cats=await env.BLOG_KV.get("cats","json")||[];var arts=await env.BLOG_KV.get("arts","json")||[];var items=cats.map(c=>{var cnt=arts.filter(a=>a.catId===c.id).length;return'<div class="art-item"><div class="art-info"><div class="art-t"><span class="art-dot" style="background:'+c.color+';width:12px;height:12px;border-radius:50%;margin-right:.5rem"></span>'+esc(c.name)+'</div><div class="art-meta">'+cnt+' \u7bc7 \u00b7 '+esc(c.id)+'</div></div><div class="art-acts"><form method="POST" action="/admin/cat/del/'+c.id+'" style="display:inline" onsubmit="return confirm(\'\u5220\u9664?\')"><button class="btn btn-sm btn-r">\u5220\u9664</button></form></div></div>'}).join("");return adminW("\u5206\u7c7b",'<h1 class="admin-h1">\u5206\u7c7b\u7ba1\u7406</h1><div class="s-card"><div class="s-card-t">\u6dfb\u52a0\u5206\u7c7b</div><form method="POST" action="/admin/cat/add" style="display:flex;gap:.75rem;flex-wrap:wrap;align-items:end"><div class="fg" style="flex:1;min-width:120px;margin-bottom:0"><label class="fl">ID</label><input type="text" name="id" class="fi" required></div><div class="fg" style="flex:1;min-width:120px;margin-bottom:0"><label class="fl">\u540d\u79f0</label><input type="text" name="name" class="fi" required></div><div class="fg" style="min-width:70px;margin-bottom:0"><label class="fl">\u989c\u8272</label><input type="color" name="color" class="fi" value="#0284c7" style="height:42px;padding:4px"></div><button type="submit" class="btn btn-g" style="height:42px">\u6dfb\u52a0</button></form></div><div class="art-list">'+(items||"\u6682\u65e0")+'</div>',"c")}
async function actAddCat(req,env){var fd=await req.formData();var id=(fd.get("id")||"").trim().toLowerCase();var name=(fd.get("name")||"").trim();var color=fd.get("color")||"#0284c7";if(!id||!name)return redir("/admin/cats");var cats=await env.BLOG_KV.get("cats","json")||[];if(cats.find(c=>c.id===id))return redir("/admin/cats");cats.push({id,name,color});await env.BLOG_KV.put("cats",JSON.stringify(cats));return redir("/admin/cats")}
async function actDelCat(env,id){var cats=await env.BLOG_KV.get("cats","json")||[];cats=cats.filter(c=>c.id!==id);await env.BLOG_KV.put("cats",JSON.stringify(cats));return redir("/admin/cats")}
async function pgSettings(env){var s=await env.BLOG_KV.get("settings","json")||{};return adminW("\u8bbe\u7f6e",'<h1 class="admin-h1">\u8bbe\u7f6e</h1><div class="s-card"><div class="s-card-t">\u57fa\u672c</div><form method="POST" action="/admin/sett/save"><input type="hidden" name="action" value="info"><div class="fg"><label class="fl">\u535a\u5ba2\u540d</label><input type="text" name="blogName" class="fi" value="'+esc(s.blogName)+'"></div><button type="submit" class="btn btn-p">\u4fdd\u5b58</button></form></div><div class="s-card"><div class="s-card-t">\u5bc6\u7801</div><form method="POST" action="/admin/sett/save"><input type="hidden" name="action" value="pwd"><div class="fg"><label class="fl">\u5f53\u524d</label><input type="password" name="oldPwd" class="fi" required></div><div class="fg"><label class="fl">\u65b0</label><input type="password" name="newPwd" class="fi" required minlength="4"></div><div class="fg"><label class="fl">\u786e\u8ba4</label><input type="password" name="newPwd2" class="fi" required minlength="4"></div><button type="submit" class="btn btn-a">\u4fee\u6539</button></form></div>',"s")}
async function actSaveSett(req,env){var fd=await req.formData();var action=fd.get("action");var settings=await env.BLOG_KV.get("settings","json")||{};if(action==="info"){settings.blogName=(fd.get("blogName")||"\u674e\u529b\u7684blog").trim();await env.BLOG_KV.put("settings",JSON.stringify(settings))}else if(action==="pwd"){var oldPwd=fd.get("oldPwd")||"";var newPwd=fd.get("newPwd")||"";var newPwd2=fd.get("newPwd2")||"";if(await sha(settings.salt+oldPwd)!==settings.pwdHash)return html(adminW("\u8bbe\u7f6e",'<div class="s-card"><p style="color:var(--red)">\u5bc6\u7801\u9519\u8bef</p></div>',"s"));if(newPwd!==newPwd2)return html(adminW("\u8bbe\u7f6e",'<div class="s-card"><p style="color:var(--red)">\u4e0d\u4e00\u81f4</p></div>',"s"));if(newPwd.length<4)return html(adminW("\u8bbe\u7f6e",'<div class="s-card"><p style="color:var(--red)">\u81f3\u5c114\u4f4d</p></div>',"s"));settings.salt=hex(16);settings.pwdHash=await sha(settings.salt+newPwd);await env.BLOG_KV.put("settings",JSON.stringify(settings))}return redir("/admin/settings")}
async function actSave(req,env){var body=await req.json();var id=body.id||("a"+Date.now());var now=Date.now();var content=body.content||"";await env.BLOG_KV.put("c:"+id,JSON.stringify({content:content,polls:body.polls||{}}));for(var[pid,pdata]of Object.entries(body.polls||{})){var existing=await env.BLOG_KV.get("poll:"+pid,"json");if(!existing){await env.BLOG_KV.put("poll:"+pid,JSON.stringify({title:pdata.title,options:(pdata.options||[]).map(t=>({text:t,votes:0})),voters:{}}))}else{existing.title=pdata.title;existing.options=(pdata.options||[]).map(t=>{var old=existing.options.find(o=>o.text===t);return{text:t,votes:old?old.votes:0}});await env.BLOG_KV.put("poll:"+pid,JSON.stringify(existing))}}var arts=await env.BLOG_KV.get("arts","json")||[];var idx=arts.findIndex(a=>a.id===id);if(idx>=0){arts[idx].title=body.title;arts[idx].catId=body.catId;arts[idx].updatedAt=now;arts[idx].excerpt=excerpt(content)}else{arts.unshift({id,title:body.title,catId:body.catId,createdAt:now,updatedAt:now,pinned:false,excerpt:excerpt(content)})}await env.BLOG_KV.put("arts",JSON.stringify(arts));return redir("/admin/dashboard")}
async function actDel(env,id){var arts=await env.BLOG_KV.get("arts","json")||[];arts=arts.filter(a=>a.id!==id);await env.BLOG_KV.put("arts",JSON.stringify(arts));await env.BLOG_KV.delete("c:"+id);return redir("/admin/dashboard")}
async function actPin(env,id){var arts=await env.BLOG_KV.get("arts","json")||[];var art=arts.find(a=>a.id===id);if(art){art.pinned=!art.pinned;art.updatedAt=Date.now();await env.BLOG_KV.put("arts",JSON.stringify(arts))}return redir("/admin/dashboard")}
async function apiPollVote(req,env){var{pollId,optionIndex}=await req.json();if(!pollId||optionIndex===undefined)return jsonR({error:"\u53c2\u6570"},400);var poll=await env.BLOG_KV.get("poll:"+pollId,"json");if(!poll)return jsonR({error:"\u4e0d\u5b58\u5728"},404);var ip=req.headers.get("CF-Connecting-IP")||"unknown";if(poll.voters&&poll.voters[ip]!==undefined)return jsonR({error:"\u5df2\u6295"},400);if(optionIndex<0||optionIndex>=poll.options.length)return jsonR({error:"\u65e0\u6548"},400);poll.options[optionIndex].votes++;if(!poll.voters)poll.voters={};poll.voters[ip]=optionIndex;await env.BLOG_KV.put("poll:"+pollId,JSON.stringify(poll));return jsonR({success:true})}
async function apiUpload(req,env){var{data,type}=await req.json();if(!data)return jsonR({error:"\u65e0"},400);if(data.length>3000000)return jsonR({error:"\u5927"},400);var id="img"+Date.now()+hex(4);await env.BLOG_KV.put("image:"+id,JSON.stringify({data,type:type||"image/png"}));return jsonR({url:"/img/"+id})}
async function apiImg(env,id){var raw=await env.BLOG_KV.get("image:"+id);if(!raw)return new Response("Not Found",{status:404});var{data,type}=JSON.parse(raw);var b64=data.includes(",")?data.split(",")[1]:data;var bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));return new Response(bin,{headers:{"Content-Type":type||"image/png","Cache-Control":"public, max-age=31536000"}})}
function favico(){return new Response('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#d4af37"/><stop offset=".5" stop-color="#c9b56a"/><stop offset="1" stop-color="#c0c0c0"/></linearGradient></defs><path d="M6 26C2 26 2 22 5 20C4 18 5 15 9 14C10 10 15 9 18 12C20 10 24 11 25 15C28 14 30 16 29 20C31 21 31 24 28 26Z" fill="url(#g)"/><text x="13" y="25" font-family="Georgia,serif" font-size="12" font-weight="bold" fill="white">L</text></svg>',{headers:{"Content-Type":"image/svg+xml","Cache-Control":"public, max-age=86400"}})}